<?php

namespace AppBundle\Repository;

/**
 * NewsletterSubscriberRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsletterSubscriberRepository extends \Doctrine\ORM\EntityRepository
{
}
