<?php

namespace AppBundle\Repository;

/**
 * PostalCodeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostalCodeRepository extends \Doctrine\ORM\EntityRepository
{
}
