<?php

namespace AppBundle\Repository;

/**
 * WorkshopRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WorkshopRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAll()
    {
        $qb = $this->getEntityManager()->createQueryBuilder();

        $query = $qb->select('w')
            ->from('AppBundle:Workshop', 'w')
            ->join('w.user', 'u', 'WITH', 'u.id = w.user')
            ->addSelect('u')
            ->orderBy('w.start', 'DESC')
            ->getQuery();

        return $query->getResult();
    }
}
