# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    app.twig_extension:
        class: AppBundle\Twig\AppExtension
        public: false
        tags:
            - { name: twig.extension }

    app.favorites_manager:
        class: AppBundle\Managers\FavoritesManager
        arguments: ["@doctrine.orm.entity_manager"]

    app.image_manager:
        class: AppBundle\Managers\ImageManager
        arguments: ["%assets_root%"]

    app.image_storage_manager:
        class: AppBundle\Managers\ImageStorageManager
        arguments: ["%avatars_folder%", "%sliders_folder%", "%categories_folder%"]

    app.registration:
        class: AppBundle\Service\RegistrationService
        arguments: ["@mailer", "@templating"]
